#!/usr/bin/env bash
#
# AmneziaX panel installer.
#
#   bash <(curl -fsSL https://raw.githubusercontent.com/SpecFlowdev/AmneziaX/main/scripts/install-panel.sh)
#
# Installs Docker if needed, writes /opt/amneziax/.env with generated secrets and
# brings up Postgres plus the panel. Re-running it is safe: existing secrets are
# kept and only the images are refreshed.

set -euo pipefail

REPO_RAW="${AMNEZIAX_RAW:-https://raw.githubusercontent.com/SpecFlowdev/AmneziaX/main}"
INSTALL_DIR="${AMNEZIAX_DIR:-/opt/amneziax}"
HTTP_PORT="${AMNEZIAX_HTTP_PORT:-8080}"
GRPC_PORT="${AMNEZIAX_GRPC_PORT:-9090}"
PUBLIC_URL="${AMNEZIAX_PUBLIC_URL:-}"
BUILD_LOCAL=0
ASSUME_YES=0

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BOLD=$'\033[1m'; NC=$'\033[0m'
info()  { printf '%s==>%s %s\n' "$GREEN" "$NC" "$*"; }
warn()  { printf '%s!! %s %s\n' "$YELLOW" "$NC" "$*"; }
die()   { printf '%serror:%s %s\n' "$RED" "$NC" "$*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: install-panel.sh [options]

  --dir PATH          install directory (default: $INSTALL_DIR)
  --http-port PORT    port for the web UI and API (default: $HTTP_PORT)
  --grpc-port PORT    port node agents connect to (default: $GRPC_PORT)
  --url URL           public panel URL, e.g. https://panel.example.com
  --build             build the images from this checkout instead of pulling
  -y, --yes           do not ask for confirmation
  -h, --help          show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir) INSTALL_DIR="$2"; shift 2 ;;
    --http-port) HTTP_PORT="$2"; shift 2 ;;
    --grpc-port) GRPC_PORT="$2"; shift 2 ;;
    --url) PUBLIC_URL="$2"; shift 2 ;;
    --build) BUILD_LOCAL=1; shift ;;
    -y|--yes) ASSUME_YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
done

[[ $EUID -eq 0 ]] || die "run this as root (sudo bash ...)"

# ---------------------------------------------------------------- dependencies

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    return
  fi
  info "installing Docker"
  curl -fsSL https://get.docker.com | sh || die "Docker installation failed"
  systemctl enable --now docker >/dev/null 2>&1 || true
  docker compose version >/dev/null 2>&1 || die "docker compose plugin is missing"
}

for tool in curl openssl; do
  command -v "$tool" >/dev/null 2>&1 || {
    info "installing $tool"
    if command -v apt-get >/dev/null 2>&1; then
      apt-get update -qq && apt-get install -y -qq "$tool"
    elif command -v dnf >/dev/null 2>&1; then
      dnf install -y -q "$tool"
    elif command -v yum >/dev/null 2>&1; then
      yum install -y -q "$tool"
    else
      die "please install $tool and re-run"
    fi
  }
done

install_docker

# ---------------------------------------------------------------- configuration

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

if [[ -z "$PUBLIC_URL" ]]; then
  detected_ip="$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')"
  PUBLIC_URL="http://${detected_ip:-localhost}:${HTTP_PORT}"
fi

# The gRPC host is what a node agent dials, so it must be reachable from outside.
grpc_host="${PUBLIC_URL#*://}"
grpc_host="${grpc_host%%[:/]*}"

if [[ -f .env ]]; then
  info "keeping the existing secrets in $INSTALL_DIR/.env"
  # shellcheck disable=SC1091
  set -a; source .env; set +a
else
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  JWT_SECRET="$(openssl rand -hex 32)"
  PANEL_ADMIN_PASSWORD="$(openssl rand -base64 15 | tr -d '/+=' | cut -c1-16)"
  PANEL_ADMIN_USERNAME="admin"
  FRESH_INSTALL=1
fi

cat > .env <<EOF
# Generated by install-panel.sh — keep this file private.
POSTGRES_USER=amneziax
POSTGRES_DB=amneziax
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}

PANEL_ADMIN_USERNAME=${PANEL_ADMIN_USERNAME:-admin}
PANEL_ADMIN_PASSWORD=${PANEL_ADMIN_PASSWORD}

PANEL_HTTP_PORT=${HTTP_PORT}
PANEL_GRPC_PORT=${GRPC_PORT}
PANEL_PUBLIC_URL=${PUBLIC_URL}
PANEL_GRPC_PUBLIC_HOST=${grpc_host}
PANEL_GRPC_PUBLIC_PORT=${GRPC_PORT}

SUBSCRIPTION_TITLE=AmneziaX
LOG_LEVEL=info
EOF
chmod 600 .env

if [[ $BUILD_LOCAL -eq 0 ]]; then
  info "fetching the compose file"
  curl -fsSL -o docker-compose.yml "${REPO_RAW}/deploy/docker-compose.yml" \
    || die "could not download the compose file"
  # Without a local build context the compose file must not try to build.
  sed -i '/^    build:/,/^      dockerfile:.*$/d' docker-compose.yml
fi

# ---------------------------------------------------------------- launch

if [[ $ASSUME_YES -eq 0 && -t 0 ]]; then
  printf '\n%sAbout to install AmneziaX in %s%s\n' "$BOLD" "$INSTALL_DIR" "$NC"
  printf '  panel URL : %s\n' "$PUBLIC_URL"
  printf '  http port : %s\n  node port : %s\n\n' "$HTTP_PORT" "$GRPC_PORT"
  read -r -p 'Continue? [Y/n] ' answer
  [[ -z "$answer" || "$answer" =~ ^[Yy]$ ]] || die "aborted"
fi

info "starting the stack"
if [[ $BUILD_LOCAL -eq 1 ]]; then
  docker compose -f deploy/docker-compose.yml --env-file .env up -d --build
else
  docker compose --env-file .env pull
  docker compose --env-file .env up -d
fi

info "waiting for the panel to answer"
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${HTTP_PORT}/api/health" >/dev/null 2>&1; then
    ready=1
    break
  fi
  sleep 2
done

if [[ "${ready:-0}" != 1 ]]; then
  warn "the panel did not answer yet — check: docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f panel"
  exit 1
fi

cat <<EOF

${GREEN}${BOLD}AmneziaX is running.${NC}

  URL       : ${PUBLIC_URL}
  Username  : ${PANEL_ADMIN_USERNAME:-admin}
$( [[ "${FRESH_INSTALL:-0}" == 1 ]] && printf '  Password  : %s\n' "$PANEL_ADMIN_PASSWORD" )
  Node port : ${GRPC_PORT} (open this in your firewall so agents can connect)

Config and secrets live in ${INSTALL_DIR}/.env

Next steps:
  1. Sign in and change the password under Settings.
  2. Create a node; the panel gives you a one-line install command for it.
  3. Add a host for your inbound, then create users.

Manage the stack with:
  cd ${INSTALL_DIR} && docker compose --env-file .env [ps|logs -f|restart|down]

EOF
